stages:
    - build
    - test
    - publish

build:
    stage: build
    image: node:20-alpine
    before_script:
        - npm ci
        - npm run prisma:generate
    script:
        - npm run build
    artifacts:
        paths:
            - "build/"
            - "prisma/"
            - "node_modules/"
        expire_in: 1h

test:
    stage: test
    image: node:20-alpine
    timeout: 6 minutes
    services:
    - name: postgres:15-alpine 
      alias: db
    variables:
        POSTGRES_USER: prisma
        POSTGRES_PASSWORD: prisma
        POSTGRES_DB: appdb
        DATABASE_URL: postgres://prisma:prisma@db:5432/appdb
    dependencies:
        - build
    before_script:
        - |
            for path in build prisma node_modules; do
                if [ ! -e "$path" ]; then
                echo "‼️ Required artifact '$path' not found. Aborting."
                exit 1
                fi
            done
        - npm run prisma:generate
    script:
        - npm run prisma:prod
        - npm run start &
        - apk add --no-cache busybox-extras
        - echo "Probing TCP port 5432 on db:" && nc -zv db 5432
        - npm run test
    

publish:
    stage: publish
    image: docker:28.2.2-alpine3.22
    dependencies:
        - test
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    script:
        - docker build -t instarlinz/fasttest:lastest .
        - docker push instarlinz/fasttest:lastest
    only:
        - master