version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: registry.ilcloud.tech/mds_7_case_digital_brief_platform-frontend:latest
