include:
  - docker-compose-infra.yaml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SESSION_SECRET: ${SESSION_SECRET}
        ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
        NODE_ENV: dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    init: true
    environment:
      NODE_ENV: dev
      USE_HTTPS: false
      DATABASE_URL: postgresql://prisma:prisma@db:5432/appdb
      BASE_URL: http://localhost:3000
    env_file:
      - .env
    volumes:
      - .:/app:delegated
      - /app/node_modules
    working_dir: /app
    networks:
      - prisma-network
    entrypoint: ["./entrypoint.sh"]
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

networks:
  prisma-network: {}