include:
  - docker-compose-infra.yaml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        SESSION_SECRET: ${SESSION_SECRET}
        NODE_ENV: prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    init: true
    environment:
      NODE_ENV: prod
      USE_HTTPS: false
      DATABASE_URL: postgresql://prisma:prisma@db:5432/appdb
      BASE_URL: http://localhost:3000
    env_file:
      - .env
    networks:
      - prisma-network
    entrypoint: ["./entrypoint.sh"]
    command: npm run start
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

networks:
  prisma-network: {}