version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    image: registry.ilcloud.tech/mds_7_case_digital_brief_platform-frontend:latest
