services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio-data:/data
    networks:
      - prisma-network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - db-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    networks:
      - prisma-network

volumes:
  minio-data:
  db-data: